% % create a folder to place all saved images in

analysis_folder_name_parent = 'nb56-all-simulation-analysis';

analysis_folder_name = '2019-07-11';

current_time = datetime('now','Format','yyyy-MM-dd-HHmmss');

newfolder = sprintf('%s-cumulative-discharge-rate-plotter',current_time(1));

current_directory = sprintf('%s',pwd);

path_to_analysis_files = fullfile(current_directory,analysis_folder_name_parent,analysis_folder_name);

fullpath = fullfile(current_directory,newfolder);

cd(path_to_analysis_files);

sim_filenames = dir('*discharge-rate-pos*');

cd(current_directory);

% sim_filenames = [string('2019-06-25-182633-discharge-rate-pos-5-sig.txt');
%     string('2019-06-25-182928-discharge-rate-pos-5-sig.txt');
%     string('2019-06-25-183234-discharge-rate-pos-5-sig.txt');
%     string('2019-06-25-183455-discharge-rate-pos-5-sig.txt');
%     string('2019-06-25-183745-discharge-rate-pos-5-sig.txt');
%     string('2019-06-25-184050-discharge-rate-pos-5-sig.txt');
%     string('2019-06-25-184341-discharge-rate-pos-5-sig.txt');
%     string('2019-06-25-184650-discharge-rate-pos-5-sig.txt');
%     string('2019-06-25-184930-discharge-rate-pos-5-sig.txt')];

num_files = length(sim_filenames);

sizeset = [6 Inf];

formatSpec = '%f %f %f %f %f %f';

one_big_data_set = [];

this_set_indices = [];

number_rows = 0;

for i=1:num_files
    
    fileID = fopen(fullfile(current_directory,'nb56-discharge-rates-all-sims',...
        sprintf('%s',sim_filenames(i))),'r');

    data_set = fscanf(fileID, formatSpec, sizeset);

    data_set = data_set';
    
    number_rows_this_set = length(data_set(:,1));
    
    for j = 1:number_rows_this_set
        
        number_rows = number_rows + 1;
        
        one_big_data_set(end+1,:) = [number_rows i data_set(j,:)];
        
    end
    
   this_set_indices(end+1,:) = [(number_rows - number_rows_this_set + 1) number_rows];
    
end

for i = 1:num_files
    
    one_big_data_set(this_set_indices(1,1):this_set_indices(1,2),1),...
        zeros(length(one_big_data_set(this_set_indices(1,1):this_set_indices(1,2),1)),1),...
        one_big_data_set(this_set_indices(1,1):this_set_indices(1,2),5),...
        zeros(length(one_big_data_set(this_set_indices(1,1):this_set_indices(1,2),7)),1),...
        one_big_data_set(this_set_indices(2,1):this_set_indices(2,2),1),...
        zeros(length(one_big_data_set(this_set_indices(2,1):this_set_indices(2,2),1)),1),...
        one_big_data_set(this_set_indices(2,1):this_set_indices(2,2),5),...
        zeros(length(one_big_data_set(this_set_indices(2,1):this_set_indices(2,2),7)),1)

end






% row 3 = dph (5 sigma)
% row 4 = dph_std (5 sigma)
% row 5 = median discharge size (5 sigma)
% row 6 = dph (cutoff)
% row 7 = dph_std (cutoff)
% row 8 = median discharge size (cutoff)

hv_plot_xy_errors('ramp simulation (dis)charging voltage plotted over all','',...
    1,0,fullpath,sprintf('nb56-discharge-rates-all-sims'),...
    one_big_data_set(this_set_indices(1,1):this_set_indices(1,2),1),...
    zeros(length(one_big_data_set(this_set_indices(1,1):this_set_indices(1,2),1)),1),...
    one_big_data_set(this_set_indices(1,1):this_set_indices(1,2),5),...
    zeros(length(one_big_data_set(this_set_indices(1,1):this_set_indices(1,2),7)),1),...
    one_big_data_set(this_set_indices(2,1):this_set_indices(2,2),1),...
    zeros(length(one_big_data_set(this_set_indices(2,1):this_set_indices(2,2),1)),1),...
    one_big_data_set(this_set_indices(2,1):this_set_indices(2,2),5),...
    zeros(length(one_big_data_set(this_set_indices(2,1):this_set_indices(2,2),7)),1),...
    one_big_data_set(this_set_indices(3,1):this_set_indices(3,2),1),...
    zeros(length(one_big_data_set(this_set_indices(3,1):this_set_indices(3,2),1)),1),...
    one_big_data_set(this_set_indices(3,1):this_set_indices(3,2),5),...
    zeros(length(one_big_data_set(this_set_indices(3,1):this_set_indices(3,2),7)),1),...
    one_big_data_set(this_set_indices(4,1):this_set_indices(4,2),1),...
    zeros(length(one_big_data_set(this_set_indices(4,1):this_set_indices(4,2),1)),1),...
    one_big_data_set(this_set_indices(4,1):this_set_indices(4,2),5),...
    zeros(length(one_big_data_set(this_set_indices(4,1):this_set_indices(4,2),7)),1),...
    one_big_data_set(this_set_indices(5,1):this_set_indices(5,2),1),...
    zeros(length(one_big_data_set(this_set_indices(5,1):this_set_indices(5,2),1)),1),...
    one_big_data_set(this_set_indices(5,1):this_set_indices(5,2),5),...
    zeros(length(one_big_data_set(this_set_indices(5,1):this_set_indices(5,2),7)),1),...
    one_big_data_set(this_set_indices(6,1):this_set_indices(6,2),1),...
    zeros(length(one_big_data_set(this_set_indices(6,1):this_set_indices(6,2),1)),1),...
    one_big_data_set(this_set_indices(6,1):this_set_indices(6,2),5),...
    zeros(length(one_big_data_set(this_set_indices(6,1):this_set_indices(6,2),7)),1),...
    one_big_data_set(this_set_indices(7,1):this_set_indices(7,2),1),...
    zeros(length(one_big_data_set(this_set_indices(7,1):this_set_indices(7,2),1)),1),...
    one_big_data_set(this_set_indices(7,1):this_set_indices(7,2),5),...
    zeros(length(one_big_data_set(this_set_indices(7,1):this_set_indices(7,2),7)),1),...
    one_big_data_set(this_set_indices(8,1):this_set_indices(8,2),1),...
    zeros(length(one_big_data_set(this_set_indices(8,1):this_set_indices(8,2),1)),1),...
    one_big_data_set(this_set_indices(8,1):this_set_indices(8,2),5),...
    zeros(length(one_big_data_set(this_set_indices(8,1):this_set_indices(8,2),7)),1),...
    one_big_data_set(this_set_indices(9,1):this_set_indices(9,2),1),...
    zeros(length(one_big_data_set(this_set_indices(9,1):this_set_indices(9,2),1)),1),...
    one_big_data_set(this_set_indices(9,1):this_set_indices(9,2),5),...
    zeros(length(one_big_data_set(this_set_indices(9,1):this_set_indices(9,2),7)),1));